name: Docker (Gitea)

on:
  push:
    branches: [ "**" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main", "latest" ]

jobs:
  build_on_gitea:
    runs-on: ubuntu-latest

    env:
      DOMAIN: ${{ secrets.DOMAIN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."${{ env.DOMAIN }}"]
              http = true
              insecure = true

      - name: Normalize repository name
        id: normalize
        run: echo "repo_lc=$(echo $GITEA_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        env:
          GITEA_REPOSITORY: ${{ gitea.repository }}

      - name: Log into Gitea Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOMAIN }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOMAIN }}/${{ steps.normalize.outputs.repo_lc }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ env.DOMAIN }}/${{ steps.normalize.outputs.repo_lc }}:buildcache
          cache-to: type=registry,ref=${{ env.DOMAIN }}/${{ steps.normalize.outputs.repo_lc }}:buildcache,mode=max
